---
title: "While loop"
author: "Siddharth"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## While loop

```{r}

mylist <- list()
counter <- 1
mynumbers <- c(4,5,1,2,6,2,4,6,6,2)
mycondition <- mynumbers[counter]<=5


while(mycondition){
  mylist[[counter]] <- diag(mynumbers[counter])
  counter <- counter + 1
  if(counter <= length(mynumbers)){
    mycondition <- mynumbers[counter] <= 5
  }else{
    mycondition <- FALSE
  }
  
}
mylist

```

## Infinite while loop

```{r}
y <- 5

while(y<10){
  print(y^3)
  }
```


## Break Statement
Break statement is used to preemptively terminate a loop

```{r}
foo <- 5
bar <- c(2,3,1.1,4,0,4.1,3)

loop1.result <- rep(NA,length(bar))
loop1.result

for(i in 1:length(bar)){
  temp <- foo/bar[i]
  if(is.finite(temp)){
    loop1.result[i] <- temp
  }else{
    break
    }
}

loop1.result
```

## Next statement
Instead of breaking and completely ending a loop, you can use next to
simply advance to the next iteration and continue execution

```{r}
foo <- 5
bar <- c(2,3,1.1,4,0,4.1,3)

loop1.result <- rep(NA,length(bar))
loop1.result

for(i in 1:length(bar)){
  temp <- foo/bar[i]
  if(is.finite(temp)){
    loop1.result[i] <- temp
  }else{
    next
    }
}

loop1.result

```

## Example used in concept understanding

```{r}

x <- 5
while(x>2){
  print(x)
  x <- x+3
  if(x>20)
    break
}

alphabet <- LETTERS[1:7]
for(i in alphabet){
  if(i=="C"){
    next
  }
    print(i)
}
```
